local vim = vim

vim.g.NERDTreeAutoDeleteBuffer = 1
vim.g.NERDTreeCascadeSingleChildDir = 0
vim.g.NERDTreeCreatePrefix = 'silent keepalt keepjumps'
vim.g.NERDTreeMinimalMenu = 1
vim.g.NERDTreeMinimalUI = 1
vim.g.NERDTreeQuitOnOpen = 0
vim.g.NERDTreeShowHidden = 0
vim.g.NERDTreeStatusline = ''
vim.g.mapleader = ' '
vim.g.maplocalleader = ','
vim.g.plug_window = 'noautocmd vertical topleft new'
vim.o.autoindent = true
vim.o.autoread = true
vim.o.autowrite = true
vim.o.autowriteall = true
vim.o.backup = false
vim.o.breakindent = true
vim.o.cindent = true
vim.o.clipboard = 'unnamedplus'
vim.o.cmdheight = 1
vim.o.completeopt = 'menuone,noselect,longest'
vim.o.conceallevel = 2
vim.o.copyindent = true
vim.o.cursorcolumn = false
vim.o.cursorline = false
vim.o.encoding = 'UTF-8'
vim.o.expandtab = true
vim.o.foldexpr = "nvim_treesitter#foldexpr()"
vim.o.foldlevelstart = 1
vim.o.foldmethod = "expr"
vim.o.foldminlines = 1
vim.o.grepprg = "rg -i -n -w --vimgrep $*"
vim.o.hidden = true
vim.o.history = 500
vim.o.hlsearch = true
vim.o.ignorecase = true
vim.o.inccommand = 'nosplit'
vim.o.incsearch = true
vim.o.joinspaces = false
vim.o.laststatus = 2
vim.o.linespace = 0
vim.o.list = true
vim.o.magic = true
vim.o.modeline = true
vim.o.modelines = 3
vim.o.mouse = ''
vim.o.mouse = 'a'
vim.o.number = true
vim.o.relativenumber = false
vim.o.scrolloff=0
vim.o.shiftround = true
vim.o.shiftwidth=2
vim.o.showcmd = true
vim.o.showmatch = true
vim.o.showmode = false
vim.o.showtabline = 1
vim.o.sidescroll = 5
vim.o.sidescrolloff = 4
vim.o.signcolumn = 'no'
vim.o.smartcase = true
vim.o.smartindent = true
vim.o.softtabstop = 2
vim.o.splitbelow = false
vim.o.splitright = false
vim.o.swapfile = false
vim.o.tabstop = 2
vim.o.termguicolors = true
vim.o.timeoutlen = 300
vim.o.title = true
vim.o.ttimeout = true
vim.o.undofile = true
vim.o.updatetime = 250
vim.o.visualbell = false
vim.o.wildmenu = true
vim.o.wildmode = 'full'
vim.o.wrap = false
vim.o.writebackup = false
vim.opt.fillchars = { stlnc = ' ', vert = '┃', fold = '-', diff = '-' }
vim.opt.listchars = { tab = '◁∙▷', trail = '∙', precedes = '<', extends = '>' }
vim.opt.path = { './**', '' }
vim.opt.shortmess:append { c = true, S = true }
vim.opt.tags:prepend { "./.git/tags" }
vim.opt.wildignore:append { "*.o" , "*~" , "*.pyc", "*/.git/*" , "*/.hg/*" , "*/.svn/*" , "*/.DS_Store" }
-- vim.cmd('set guicursor=n-v-c:block,i-ci-ve:ver25,r-cr:hor20,o:hor50')
